/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package neutrino.PacketsInformation;

/**
 *
 * @author Julián
 */
public class ServerEvents {
	// 2850 some idiot thing
    public static int InitSystem = 2437;
    public static int SetHome = 1893;
    //public static int Gifts = 1608;
    public static int SetFavs = 601;
    public static int InventoryWarn = 1464;
    public static int FuseRights = 2112;
    public static int MoreData = 1870;
    public static int UnData = 2186;
    public static int Pixels = 2653;
    public static int Snow = 2207;
    public static int Alert = 767;
    public static int LeavingRoom = 3384;
    public static int LeaveRoom = 312;
    public static int NavigatorShowPublics = 2884;
    public static int MyInformation = 2720;
    public static int SendCredits = 464;
    public static int SendAchievements = 229;
    public static int SendCatalogPage = 2596;
    public static int SendCatalogPageData = 2220;
    public static int SendNavCategories = 463;
    public static int MOD_SHOWUSERINFO = 2718; // response to 876
    public static int MOD_SHOWROOMDATA = 2403;
    public static int MOD_SHOWROOMCHATLOG = 2161;
    public static int MOD_ADDISSUE = 2113;
    public static int MOD_SHOWCFHCHATLOG = 3479;
    public static int MOD_PIKCUPISSUE = 3730;
    public static int MOD_SHOWUSERCHATLOG = 2855;
    public static int ClubBuy = 1237;
    public static int ClubData = 270;
    public static int ModTools = 2294;
    public static int LookRooms = 840;
    public static int CanTrade = 2606;
    public static int TradeObject = 371;
    public static int AcceptTrade = 816;
    public static int TradingConfirmation = 213;
    public static int EndTrade = 595;
    public static int RemoveFromInventary = 2379;
    public static int TradeCancelled = 3290;
    public static int WatchProfile = 2885;
    public static int CanCreateNewRoom = 3715;
    public static int CreateNewRoom = 3489;
    public static int InitRoomProcess = 3108;
    public static int DoorbellNoAnswer = 794;
    public static int WaitingForDoorBell = 471; // + string ("");
    public static int InvalidPassword = 312;
    public static int ValidPassword = 141;
    public static int GoodDoorbell = 1143; // + string ("");
    public static int WatchDoorBell = 471; // + string ("name");
    public static int RoomData1 = 1020;
    public static int Papers = 1047;
    public static int LoadRightsOnRoom = 2845;
    public static int LoadUserInformation = 2170;
    public static int SomePacket = 2225;
    public static int LoadPowersOnRoom = 2585;
    public static int Whisp = 1672;
    public static int RoomRating = 1550;
    public static int RoomEvents = 2707;
    public static int sWallItems = 2191;
    public static int sFloorItems = 419;
    public static int HeightMap1 = 559;
    public static int HeightMap2 = 116;
    public static int ShowTrainingPanel = 1834;
    public static int AddExperience = 1926;
    public static int WallItems = 1671;
    public static int LoadBadges = 1673;
    public static int UpdateFloorExtraData = 2775;
    public static int FloorItems = 2440;
    public static int preUserData = 1671;
    public static int UserData = 1613;
    public static int VipWallsAndFloors = 1859;
    public static int RoomPanel = 1135;
    public static int RoomData = 2956;
    public static int Talk = 2166;
    public static int Shout = 1642;
    public static int UpdateState = 2414;
    public static int Wave = 283;
    public static int Dance = 2963;
    public static int UpdateInfo = 557;
    public static int Friends = 1699;
    public static int AskToBeMyFriend = 3849; // uoooh
    public static int PendingFriends = 3089;
    public static int TalkOnChat = 2089;
    public static int UpdateFriendState = 1085;
    public static int SerializeRoomData = 2559;
    public static int GetOutOfRoom = 2225;
    public static int SendItem = 870;
    public static int SendInventory = 2538;
    public static int UpdateInventory = 68;
    public static int AddFloorItem = 1891;
    public static int AddWallItem = 2302;
    public static int UpdateFloorItem = 2540;
    public static int UpdateWallItem = 176;
    public static int RemoveFloorItem = 409;
    public static int RemoveWallItem = 1604;
    public static int RemoveWhatItem = 789;
    public static int AddItemToInventary = 553;
    public static int CurrentSnowStormPlays = 117;
    public static int FriendsLeaderBoard = 3060;
    public static int WeeklyFriendsLeaderBoard = 3758;
    public static int WeeklyGeneralLeaderBoard = 762;
    public static int GeneralLeaderBoard = 1949;
    public static int WaitingForUsers = 1511;
    public static int StillLoading = 3014;
    public static int GameUpdateState = 1424;
    public static int ShowPetRace = 3038;
    public static int IsValidPetName = 1593;
    public static int SendedPetError = 3000;
    public static int LoadPetInventary = 1194;
    public static int ShowPetInfo = 3905;
    public static int AddCharToPet = 980;
    public static int ShowEffect = 878;
    public static int ShowPows = 3883;
    public static int AcceptEvent = 3637; // 3937 ???????
    public static int SerializeBotsOnRoom = 1613;
    public static int AddUsersToGame = 1736;
    public static int UserLeaveGame = 832;
    public static int GameStartCounter = 189;
    public static int GameStarted = 350;
    public static int StageRunning = 3473;
    public static int StartSnowGame = 318;
    public static int LoadingSnowStage = 3959;
    public static int EnteredOnArena = 1033;
    public static int StageLoaded = 1074;
    public static int TalkOnSnow = 2510;
    public static int CreateGroup = 574;
    public static int SetGuildItemsData = 3537;
    public static int PurchaseGroup = 1395;
}
